import type { NextPage } from "next";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Main from "../components/Main";
import Article from "../components/Article";
import Review from "../components/Review";
import Popular from "../components/Popular";
import TopBrand from "../components/TopBrand";
import Footer from "../components/Footer";
import LatestVideo from "../components/LatestVideo";
import { getData } from "../utils/api";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { setData } from "../utils/redux/data";
import { GetStaticProps } from "next";
import Script from "next/script";
import dynamic from "next/dynamic";

const Trending = dynamic(
  () => {
    return import("../components/Trending");
  },
  { ssr: false }
);
interface props {
  data: [];
}
export const getStaticProps: GetStaticProps = async (context) => {
  const data = await getData();

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage = ({ data }) => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setData(data));
  }, []);
  return (
    <div className={styles.container}>
      <Header />
      <Main />
      <Article />
      <Review />
      <Popular />
      <LatestVideo />
      <Trending />
      <TopBrand />
      <Footer />
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"
      />
    </div>
  );
};

export default Home;
